import { chromium } from 'playwright';
const base = 'http://127.0.0.1:8090';
const b = await chromium.launch({ channel: 'chrome' });
const pg = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
pg.on('console', m => { if (m.type()==='error') errs.push(m.text()); });
pg.on('pageerror', e => errs.push('PE:'+e.message));
await pg.goto(base + '/index.html', { waitUntil: 'networkidle' });
await pg.waitForTimeout(500);
const hero = await pg.locator('.hero-name').textContent();
const highlightsVisible = await pg.locator('.highlights li').first().evaluate(el=>{const s=getComputedStyle(el);return el.getBoundingClientRect().width>0;}).catch(()=>false);
await pg.evaluate(()=>document.getElementById('portfolio').scrollIntoView());
await pg.waitForTimeout(600);
const caps = await pg.locator('.pf-cap').count();
const cards = await pg.locator('.pf-card').count();
console.log('hero:', JSON.stringify(hero));
console.log('highlights 首项存在:', highlightsVisible);
console.log('能力标签:', caps, '  作品卡:', cards);
console.log('console errors:', errs.length ? errs.slice(0,3).join(' | ') : '无');
await b.close();
process.exit(errs.length || !hero || caps!==11 || cards!==10 ? 1 : 0);
